// SPDX-License-Identifier: GPL-2.0
#ifndef __SCAN_CODE_SETS_H__
# define __SCAN_CODE_SETS_H__

# include <linux/kernel.h>
# include <linux/fs.h>

enum	ps2_key_state {
	PRESSED,
	RELEASED
};

struct scan_key_code {
	uint64_t	code;
	char	        *key_name;
	enum ps2_key_state	state;
};

struct	key_entry {
	// index inside the scan code set
	uint32_t		index;

	// Data at which the entry was performed
	struct timeval		date;

	struct list_head	head;
};

/*
  First scan code set of the PS/2 keyboards
 */

struct scan_key_code	scan_code_set_1[] = {
	{ 0x1, "escape", PRESSED },
	{ 0x2, "1", PRESSED },
	{ 0x3, "2", PRESSED },
	{ 0x4, "3", PRESSED },
	{ 0x5, "4", PRESSED },
	{ 0x6, "5", PRESSED },
	{ 0x7, "6", PRESSED },
	{ 0x8, "7", PRESSED },
	{ 0x9, "8", PRESSED },
	{ 0xa, "9", PRESSED },
	{ 0xb, "0 (zero)", PRESSED },
	{ 0xc, "-", PRESSED },
	{ 0xd, "=", PRESSED },
	{ 0xe, "backspace", PRESSED },
	{ 0xf, "tab", PRESSED },
	{ 0x10, "Q", PRESSED },
	{ 0x11, "W", PRESSED },
	{ 0x12, "E", PRESSED },
	{ 0x13, "R", PRESSED },
	{ 0x14, "T", PRESSED },
	{ 0x15, "Y", PRESSED },
	{ 0x16, "U", PRESSED },
	{ 0x17, "I", PRESSED },
	{ 0x18, "O", PRESSED },
	{ 0x19, "P", PRESSED },
	{ 0x1a, "[", PRESSED },
	{ 0x1b, "]", PRESSED },
	{ 0x1c, "enter", PRESSED },
	{ 0x1d, "left control", PRESSED },
	{ 0x1e, "A", PRESSED },
	{ 0x1f, "S", PRESSED },
	{ 0x20, "D", PRESSED },
	{ 0x21, "F", PRESSED },
	{ 0x22, "G", PRESSED },
	{ 0x23, "H", PRESSED },
	{ 0x24, "J", PRESSED },
	{ 0x25, "K", PRESSED },
	{ 0x26, "L", PRESSED },
	{ 0x27, ";", PRESSED },
	{ 0x28, "' (single quote)", PRESSED },
	{ 0x29, "` (back tick)", PRESSED },
	{ 0x2a, "left shift", PRESSED },
	{ 0x2b, "\\", PRESSED },
	{ 0x2c, "Z", PRESSED },
	{ 0x2d, "X", PRESSED },
	{ 0x2e, "C", PRESSED },
	{ 0x2f, "V", PRESSED },
	{ 0x30, "B", PRESSED },
	{ 0x31, "N", PRESSED },
	{ 0x32, "M", PRESSED },
	{ 0x33, ",", PRESSED },
	{ 0x34, ".", PRESSED },
	{ 0x35, "/", PRESSED },
	{ 0x36, "right shift", PRESSED },
	{ 0x37, "(keypad) *", PRESSED },
	{ 0x38, "left alt", PRESSED },
	{ 0x39, "space", PRESSED },
	{ 0x3a, "CapsLock", PRESSED },
	{ 0x3b, "F1", PRESSED },
	{ 0x3c, "F2", PRESSED },
	{ 0x3d, "F3", PRESSED },
	{ 0x3e, "F4", PRESSED },
	{ 0x3f, "F5", PRESSED },
	{ 0x40, "F6", PRESSED },
	{ 0x41, "F7", PRESSED },
	{ 0x42, "F8", PRESSED },
	{ 0x43, "F9", PRESSED },
	{ 0x44, "F10", PRESSED },
	{ 0x45, "NumberLock", PRESSED },
	{ 0x46, "ScrollLock", PRESSED },
	{ 0x47, "(keypad) 7", PRESSED },
	{ 0x48, "(keypad) 8", PRESSED },
	{ 0x49, "(keypad) 9", PRESSED },
	{ 0x4a, "(keypad) -", PRESSED },
	{ 0x4b, "(keypad) 4", PRESSED },
	{ 0x4c, "(keypad) 5", PRESSED },
	{ 0x4d, "(keypad) 6", PRESSED },
	{ 0x4e, "(keypad) +", PRESSED },
	{ 0x4f, "(keypad) 1", PRESSED },
	{ 0x50, "(keypad) 2", PRESSED },
	{ 0x51, "(keypad) 3", PRESSED },
	{ 0x52, "(keypad) 0", PRESSED },
	{ 0x53, "(keypad) .", PRESSED },
	{ 0x57, "F11", PRESSED },
	{ 0x58, "F12", PRESSED },
	{ 0x81, "escape", RELEASED },
	{ 0x82, "1", RELEASED },
	{ 0x83, "2", RELEASED },
	{ 0x84, "3", RELEASED },
	{ 0x85, "4", RELEASED },
	{ 0x86, "5", RELEASED },
	{ 0x87, "6", RELEASED },
	{ 0x88, "7", RELEASED },
	{ 0x89, "8", RELEASED },
	{ 0x8a, "9", RELEASED },
	{ 0x8b, "0 (zero)", RELEASED },
	{ 0x8c, "-", RELEASED },
	{ 0x8d, "=", RELEASED },
	{ 0x8e, "backspace", RELEASED },
	{ 0x8f, "tab", RELEASED },
	{ 0x90, "Q", RELEASED },
	{ 0x91, "W", RELEASED },
	{ 0x92, "E", RELEASED },
	{ 0x93, "R", RELEASED },
	{ 0x94, "T", RELEASED },
	{ 0x95, "Y", RELEASED },
	{ 0x96, "U", RELEASED },
	{ 0x97, "I", RELEASED },
	{ 0x98, "O", RELEASED },
	{ 0x99, "P", RELEASED },
	{ 0x9a, "[", RELEASED },
	{ 0x9b, "]", RELEASED },
	{ 0x9c, "enter", RELEASED },
	{ 0x9d, "left control", RELEASED },
	{ 0x9e, "A", RELEASED },
	{ 0x9f, "S", RELEASED },
	{ 0xa0, "D", RELEASED },
	{ 0xa1, "F", RELEASED },
	{ 0xa2, "G", RELEASED },
	{ 0xa3, "H", RELEASED },
	{ 0xa4, "J", RELEASED },
	{ 0xa5, "K", RELEASED },
	{ 0xa6, "L", RELEASED },
	{ 0xa7, ";", RELEASED },
	{ 0xa8, "' (single quote)", RELEASED },
	{ 0xa9, "` (back tick)", RELEASED },
	{ 0xaa, "left shift", RELEASED },
	{ 0xab, "\\", RELEASED },
	{ 0xac, "Z", RELEASED },
	{ 0xad, "X", RELEASED },
	{ 0xae, "C", RELEASED },
	{ 0xaf, "V", RELEASED },
	{ 0xb0, "B", RELEASED },
	{ 0xb1, "N", RELEASED },
	{ 0xb2, "M", RELEASED },
	{ 0xb3, ",", RELEASED },
	{ 0xb4, ".", RELEASED },
	{ 0xb5, "/", RELEASED },
	{ 0xb6, "right shift", RELEASED },
	{ 0xb7, "(keypad) *", RELEASED },
	{ 0xb8, "left alt", RELEASED },
	{ 0xb9, "space", RELEASED },
	{ 0xba, "CapsLock", RELEASED },
	{ 0xbb, "F1", RELEASED },
	{ 0xbc, "F2", RELEASED },
	{ 0xbd, "F3", RELEASED },
	{ 0xbe, "F4", RELEASED },
	{ 0xbf, "F5", RELEASED },
	{ 0xc0, "F6", RELEASED },
	{ 0xc1, "F7", RELEASED },
	{ 0xc2, "F8", RELEASED },
	{ 0xc3, "F9", RELEASED },
	{ 0xc4, "F10", RELEASED },
	{ 0xc5, "NumberLock", RELEASED },
	{ 0xc6, "ScrollLock", RELEASED },
	{ 0xc7, "(keypad) 7", RELEASED },
	{ 0xc8, "(keypad) 8", RELEASED },
	{ 0xc9, "(keypad) 9", RELEASED },
	{ 0xca, "(keypad) -", RELEASED },
	{ 0xcb, "(keypad) 4", RELEASED },
	{ 0xcc, "(keypad) 5", RELEASED },
	{ 0xcd, "(keypad) 6", RELEASED },
	{ 0xce, "(keypad) +", RELEASED },
	{ 0xcf, "(keypad) 1", RELEASED },
	{ 0xd0, "(keypad) 2", RELEASED },
	{ 0xd1, "(keypad) 3", RELEASED },
	{ 0xd2, "(keypad) 0", RELEASED },
	{ 0xd3, "(keypad) .", RELEASED },
	{ 0xd7, "F11", RELEASED },
	{ 0xd8, "F12", RELEASED },
	{ 0xe010, "(multimedia) previous track", PRESSED },
	{ 0xe019, "(multimedia) next track", PRESSED },
	{ 0xe01c, "(keypad) enter", PRESSED },
	{ 0xe01d, "right control", PRESSED },
	{ 0xe020, "(multimedia) mute", PRESSED },
	{ 0xe021, "(multimedia) calculator", PRESSED },
	{ 0xe022, "(multimedia) play", PRESSED },
	{ 0xe024, "(multimedia) stop", PRESSED },
	{ 0xe02e, "(multimedia) volume down", PRESSED },
	{ 0xe030, "(multimedia) volume up", PRESSED },
	{ 0xe032, "(multimedia) WWW home", PRESSED },
	{ 0xe035, "(keypad) /", PRESSED },
	{ 0xe038, "right alt (or altGr)", PRESSED },
	{ 0xe047, "home", PRESSED },
	{ 0xe048, "cursor up", PRESSED },
	{ 0xe049, "page up", PRESSED },
	{ 0xe04b, "cursor left", PRESSED },
	{ 0xe04d, "cursor right", PRESSED },
	{ 0xe04f, "end", PRESSED },
	{ 0xe050, "cursor down", PRESSED },
	{ 0xe051, "page down", PRESSED },
	{ 0xe052, "insert", PRESSED },
	{ 0xe053, "delete", PRESSED },
	{ 0xe05b, "left GUI", PRESSED },
	{ 0xe05c, "right GUI", PRESSED },
	{ 0xe05d, "\"apps\"", PRESSED },
	{ 0xe05e, "(ACPI) power", PRESSED },
	{ 0xe05f, "(ACPI) sleep", PRESSED },
	{ 0xe063, "(ACPI) wake", PRESSED },
	{ 0xe065, "(multimedia) WWW search", PRESSED },
	{ 0xe066, "(multimedia) WWW favorites", PRESSED },
	{ 0xe067, "(multimedia) WWW refresh", PRESSED },
	{ 0xe068, "(multimedia) WWW stop", PRESSED },
	{ 0xe069, "(multimedia) WWW forward", PRESSED },
	{ 0xe06a, "(multimedia) WWW back", PRESSED },
	{ 0xe06b, "(multimedia) my computer", PRESSED },
	{ 0xe06c, "(multimedia) email", PRESSED },
	{ 0xe06d, "(multimedia) media select", PRESSED },
	{ 0xe090, "(multimedia) previous track", RELEASED },
	{ 0xe099, "(multimedia) next track", RELEASED },
	{ 0xe09c, "(keypad) enter", RELEASED },
	{ 0xe09d, "right control", RELEASED },
	{ 0xe0a0, "(multimedia) mute", RELEASED },
	{ 0xe0a1, "(multimedia) calculator", RELEASED },
	{ 0xe0a2, "(multimedia) play", RELEASED },
	{ 0xe0a4, "(multimedia) stop", RELEASED },
	{ 0xe0ae, "(multimedia) volume down", RELEASED },
	{ 0xe0b0, "(multimedia) volume up", RELEASED },
	{ 0xe0b2, "(multimedia) WWW home", RELEASED },
	{ 0xe0b5, "(keypad) /", RELEASED },
	{ 0xe0b8, "right alt (or altGr)", RELEASED },
	{ 0xe0c7, "home", RELEASED },
	{ 0xe0c8, "cursor up", RELEASED },
	{ 0xe0c9, "page up", RELEASED },
	{ 0xe0cb, "cursor left", RELEASED },
	{ 0xe0cd, "cursor right", RELEASED },
	{ 0xe0cf, "end", RELEASED },
	{ 0xe0d0, "cursor down", RELEASED },
	{ 0xe0d1, "page down", RELEASED },
	{ 0xe0d2, "insert", RELEASED },
	{ 0xe0d3, "delete", RELEASED },
	{ 0xe0db, "left GUI", RELEASED },
	{ 0xe0dc, "right GUI", RELEASED },
	{ 0xe0dd, "\"apps\"", RELEASED },
	{ 0xe0de, "(ACPI) power", RELEASED },
	{ 0xe0df, "(ACPI) sleep", RELEASED },
	{ 0xe0e3, "(ACPI) wake", RELEASED },
	{ 0xe0e5, "(multimedia) WWW search", RELEASED },
	{ 0xe0e6, "(multimedia) WWW favorites", RELEASED },
	{ 0xe0e7, "(multimedia) WWW refresh", RELEASED },
	{ 0xe0e8, "(multimedia) WWW stop", RELEASED },
	{ 0xe0e9, "(multimedia) WWW forward", RELEASED },
	{ 0xe0ea, "(multimedia) WWW back", RELEASED },
	{ 0xe0eb, "(multimedia) my computer", RELEASED },
	{ 0xe0ec, "(multimedia) email", RELEASED },
	{ 0xe0ed, "(multimedia) media select", RELEASED },
	{ 0xe02ae037, "print screen", PRESSED },
	{ 0xe0b7e0aa, "print screen", RELEASED },
	{ 0xe11d45e19dc5, "pause", PRESSED },
};

/*
  Second scan code set of the PS/2 keyboards
 */

struct scan_key_code scan_code_set_2[] = {
	{ 0x1, "escape", PRESSED },
	{ 0x2, "1", PRESSED },
	{ 0x3, "2", PRESSED },
	{ 0x4, "3", PRESSED },
	{ 0x5, "4", PRESSED },
	{ 0x6, "5", PRESSED },
	{ 0x7, "6", PRESSED },
	{ 0x8, "7", PRESSED },
	{ 0x9, "8", PRESSED },
	{ 0xa, "9", PRESSED },
	{ 0xb, "0 (zero)", PRESSED },
	{ 0xc, "-", PRESSED },
	{ 0xd, "=", PRESSED },
	{ 0xe, "backspace", PRESSED },
	{ 0xf, "tab", PRESSED },
	{ 0x10, "Q", PRESSED },
	{ 0x11, "W", PRESSED },
	{ 0x12, "E", PRESSED },
	{ 0x13, "R", PRESSED },
	{ 0x14, "T", PRESSED },
	{ 0x15, "Y", PRESSED },
	{ 0x16, "U", PRESSED },
	{ 0x17, "I", PRESSED },
	{ 0x18, "O", PRESSED },
	{ 0x19, "P", PRESSED },
	{ 0x1a, "[", PRESSED },
	{ 0x1b, "]", PRESSED },
	{ 0x1c, "enter", PRESSED },
	{ 0x1d, "left control", PRESSED },
	{ 0x1e, "A", PRESSED },
	{ 0x1f, "S", PRESSED },
	{ 0x20, "D", PRESSED },
	{ 0x21, "F", PRESSED },
	{ 0x22, "G", PRESSED },
	{ 0x23, "H", PRESSED },
	{ 0x24, "J", PRESSED },
	{ 0x25, "K", PRESSED },
	{ 0x26, "L", PRESSED },
	{ 0x27, ";", PRESSED },
	{ 0x28, "' (single quote)", PRESSED },
	{ 0x29, "` (back tick)", PRESSED },
	{ 0x2a, "left shift", PRESSED },
	{ 0x2b, "\\", PRESSED },
	{ 0x2c, "Z", PRESSED },
	{ 0x2d, "X", PRESSED },
	{ 0x2e, "C", PRESSED },
	{ 0x2f, "V", PRESSED },
	{ 0x30, "B", PRESSED },
	{ 0x31, "N", PRESSED },
	{ 0x32, "M", PRESSED },
	{ 0x33, ",", PRESSED },
	{ 0x34, ".", PRESSED },
	{ 0x35, "/", PRESSED },
	{ 0x36, "right shift", PRESSED },
	{ 0x37, "(keypad) *", PRESSED },
	{ 0x38, "left alt", PRESSED },
	{ 0x39, "space", PRESSED },
	{ 0x3a, "CapsLock", PRESSED },
	{ 0x3b, "F1", PRESSED },
	{ 0x3c, "F2", PRESSED },
	{ 0x3d, "F3", PRESSED },
	{ 0x3e, "F4", PRESSED },
	{ 0x3f, "F5", PRESSED },
	{ 0x40, "F6", PRESSED },
	{ 0x41, "F7", PRESSED },
	{ 0x42, "F8", PRESSED },
	{ 0x43, "F9", PRESSED },
	{ 0x44, "F10", PRESSED },
	{ 0x45, "NumberLock", PRESSED },
	{ 0x46, "ScrollLock", PRESSED },
	{ 0x47, "(keypad) 7", PRESSED },
	{ 0x48, "(keypad) 8", PRESSED },
	{ 0x49, "(keypad) 9", PRESSED },
	{ 0x4a, "(keypad) -", PRESSED },
	{ 0x4b, "(keypad) 4", PRESSED },
	{ 0x4c, "(keypad) 5", PRESSED },
	{ 0x4d, "(keypad) 6", PRESSED },
	{ 0x4e, "(keypad) +", PRESSED },
	{ 0x4f, "(keypad) 1", PRESSED },
	{ 0x50, "(keypad) 2", PRESSED },
	{ 0x51, "(keypad) 3", PRESSED },
	{ 0x52, "(keypad) 0", PRESSED },
	{ 0x53, "(keypad) .", PRESSED },
	{ 0x57, "F11", PRESSED },
	{ 0x58, "F12", PRESSED },
	{ 0x81, "escape", RELEASED },
	{ 0x82, "1", RELEASED },
	{ 0x83, "2", RELEASED },
	{ 0x84, "3", RELEASED },
	{ 0x85, "4", RELEASED },
	{ 0x86, "5", RELEASED },
	{ 0x87, "6", RELEASED },
	{ 0x88, "7", RELEASED },
	{ 0x89, "8", RELEASED },
	{ 0x8a, "9", RELEASED },
	{ 0x8b, "0 (zero)", RELEASED },
	{ 0x8c, "-", RELEASED },
	{ 0x8d, "=", RELEASED },
	{ 0x8e, "backspace", RELEASED },
	{ 0x8f, "tab", RELEASED },
	{ 0x90, "Q", RELEASED },
	{ 0x91, "W", RELEASED },
	{ 0x92, "E", RELEASED },
	{ 0x93, "R", RELEASED },
	{ 0x94, "T", RELEASED },
	{ 0x95, "Y", RELEASED },
	{ 0x96, "U", RELEASED },
	{ 0x97, "I", RELEASED },
	{ 0x98, "O", RELEASED },
	{ 0x99, "P", RELEASED },
	{ 0x9a, "[", RELEASED },
	{ 0x9b, "]", RELEASED },
	{ 0x9c, "enter", RELEASED },
	{ 0x9d, "left control", RELEASED },
	{ 0x9e, "A", RELEASED },
	{ 0x9f, "S", RELEASED },
	{ 0xa0, "D", RELEASED },
	{ 0xa1, "F", RELEASED },
	{ 0xa2, "G", RELEASED },
	{ 0xa3, "H", RELEASED },
	{ 0xa4, "J", RELEASED },
	{ 0xa5, "K", RELEASED },
	{ 0xa6, "L", RELEASED },
	{ 0xa7, ";", RELEASED },
	{ 0xa8, "' (single quote)", RELEASED },
	{ 0xa9, "` (back tick)", RELEASED },
	{ 0xaa, "left shift", RELEASED },
	{ 0xab, "\\", RELEASED },
	{ 0xac, "Z", RELEASED },
	{ 0xad, "X", RELEASED },
	{ 0xae, "C", RELEASED },
	{ 0xaf, "V", RELEASED },
	{ 0xb0, "B", RELEASED },
	{ 0xb1, "N", RELEASED },
	{ 0xb2, "M", RELEASED },
	{ 0xb3, ",", RELEASED },
	{ 0xb4, ".", RELEASED },
	{ 0xb5, "/", RELEASED },
	{ 0xb6, "right shift", RELEASED },
	{ 0xb7, "(keypad) *", RELEASED },
	{ 0xb8, "left alt", RELEASED },
	{ 0xb9, "space", RELEASED },
	{ 0xba, "CapsLock", RELEASED },
	{ 0xbb, "F1", RELEASED },
	{ 0xbc, "F2", RELEASED },
	{ 0xbd, "F3", RELEASED },
	{ 0xbe, "F4", RELEASED },
	{ 0xbf, "F5", RELEASED },
	{ 0xc0, "F6", RELEASED },
	{ 0xc1, "F7", RELEASED },
	{ 0xc2, "F8", RELEASED },
	{ 0xc3, "F9", RELEASED },
	{ 0xc4, "F10", RELEASED },
	{ 0xc5, "NumberLock", RELEASED },
	{ 0xc6, "ScrollLock", RELEASED },
	{ 0xc7, "(keypad) 7", RELEASED },
	{ 0xc8, "(keypad) 8", RELEASED },
	{ 0xc9, "(keypad) 9", RELEASED },
	{ 0xca, "(keypad) -", RELEASED },
	{ 0xcb, "(keypad) 4", RELEASED },
	{ 0xcc, "(keypad) 5", RELEASED },
	{ 0xcd, "(keypad) 6", RELEASED },
	{ 0xce, "(keypad) +", RELEASED },
	{ 0xcf, "(keypad) 1", RELEASED },
	{ 0xd0, "(keypad) 2", RELEASED },
	{ 0xd1, "(keypad) 3", RELEASED },
	{ 0xd2, "(keypad) 0", RELEASED },
	{ 0xd3, "(keypad) .", RELEASED },
	{ 0xd7, "F11", RELEASED },
	{ 0xd8, "F12", RELEASED },
	{ 0xe010, "(multimedia) previous track", PRESSED },
	{ 0xe019, "(multimedia) next track", PRESSED },
	{ 0xe01c, "(keypad) enter", PRESSED },
	{ 0xe01d, "right control", PRESSED },
	{ 0xe020, "(multimedia) mute", PRESSED },
	{ 0xe021, "(multimedia) calculator", PRESSED },
	{ 0xe022, "(multimedia) play", PRESSED },
	{ 0xe024, "(multimedia) stop", PRESSED },
	{ 0xe02e, "(multimedia) volume down", PRESSED },
	{ 0xe030, "(multimedia) volume up", PRESSED },
	{ 0xe032, "(multimedia) WWW home", PRESSED },
	{ 0xe035, "(keypad) /", PRESSED },
	{ 0xe038, "right alt (or altGr)", PRESSED },
	{ 0xe047, "home", PRESSED },
	{ 0xe048, "cursor up", PRESSED },
	{ 0xe049, "page up", PRESSED },
	{ 0xe04b, "cursor left", PRESSED },
	{ 0xe04d, "cursor right", PRESSED },
	{ 0xe04f, "end", PRESSED },
	{ 0xe050, "cursor down", PRESSED },
	{ 0xe051, "page down", PRESSED },
	{ 0xe052, "insert", PRESSED },
	{ 0xe053, "delete", PRESSED },
	{ 0xe05b, "left GUI", PRESSED },
	{ 0xe05c, "right GUI", PRESSED },
	{ 0xe05d, "\"apps\"", PRESSED },
	{ 0xe05e, "(ACPI) power", PRESSED },
	{ 0xe05f, "(ACPI) sleep", PRESSED },
	{ 0xe063, "(ACPI) wake", PRESSED },
	{ 0xe065, "(multimedia) WWW search", PRESSED },
	{ 0xe066, "(multimedia) WWW favorites", PRESSED },
	{ 0xe067, "(multimedia) WWW refresh", PRESSED },
	{ 0xe068, "(multimedia) WWW stop", PRESSED },
	{ 0xe069, "(multimedia) WWW forward", PRESSED },
	{ 0xe06a, "(multimedia) WWW back", PRESSED },
	{ 0xe06b, "(multimedia) my computer", PRESSED },
	{ 0xe06c, "(multimedia) email", PRESSED },
	{ 0xe06d, "(multimedia) media select", PRESSED },
	{ 0xe090, "(multimedia) previous track", RELEASED },
	{ 0xe099, "(multimedia) next track", RELEASED },
	{ 0xe09c, "(keypad) enter", RELEASED },
	{ 0xe09d, "right control", RELEASED },
	{ 0xe0a0, "(multimedia) mute", RELEASED },
	{ 0xe0a1, "(multimedia) calculator", RELEASED },
	{ 0xe0a2, "(multimedia) play", RELEASED },
	{ 0xe0a4, "(multimedia) stop", RELEASED },
	{ 0xe0ae, "(multimedia) volume down", RELEASED },
	{ 0xe0b0, "(multimedia) volume up", RELEASED },
	{ 0xe0b2, "(multimedia) WWW home", RELEASED },
	{ 0xe0b5, "(keypad) /", RELEASED },
	{ 0xe0b8, "right alt (or altGr)", RELEASED },
	{ 0xe0c7, "home", RELEASED },
	{ 0xe0c8, "cursor up", RELEASED },
	{ 0xe0c9, "page up", RELEASED },
	{ 0xe0cb, "cursor left", RELEASED },
	{ 0xe0cd, "cursor right", RELEASED },
	{ 0xe0cf, "end", RELEASED },
	{ 0xe0d0, "cursor down", RELEASED },
	{ 0xe0d1, "page down", RELEASED },
	{ 0xe0d2, "insert", RELEASED },
	{ 0xe0d3, "delete", RELEASED },
	{ 0xe0db, "left GUI", RELEASED },
	{ 0xe0dc, "right GUI", RELEASED },
	{ 0xe0dd, "\"apps\"", RELEASED },
	{ 0xe0de, "(ACPI) power", RELEASED },
	{ 0xe0df, "(ACPI) sleep", RELEASED },
	{ 0xe0e3, "(ACPI) wake", RELEASED },
	{ 0xe0e5, "(multimedia) WWW search", RELEASED },
	{ 0xe0e6, "(multimedia) WWW favorites", RELEASED },
	{ 0xe0e7, "(multimedia) WWW refresh", RELEASED },
	{ 0xe0e8, "(multimedia) WWW stop", RELEASED },
	{ 0xe0e9, "(multimedia) WWW forward", RELEASED },
	{ 0xe0ea, "(multimedia) WWW back", RELEASED },
	{ 0xe0eb, "(multimedia) my computer", RELEASED },
	{ 0xe0ec, "(multimedia) email", RELEASED },
	{ 0xe0ed, "(multimedia) media select", RELEASED },
	{ 0xe02ae037, "print screen", PRESSED },
	{ 0xe0b7e0aa, "print screen", RELEASED },
	{ 0xe11d45e19dc5, "pause", PRESSED },
};

#endif /* __SCAN_CODE_SETS_H__ */
